### ISSUE TITLE
Enable/Disable checkpoints fails if Checkpoints node in payload is not json

### ISSUE THREAD

**Issue by jmloeffler** [clearent/uptrends#1]
Then enable-checkpoint.py and disable-checkpoint.py scripts assume that the `Checkpoints` node in the GET /v3/probes payload is json and fails if the contents are not valid json.  This seems to happen if the Asia - Use only primary checkpoints option is not checked.  Checking this box (even if no Asia checkpoints are used) makes the Checkpoints node into a json object.  Unchecked, it is a simple comma-separated string.  The scripts should be able to handle either case.

```
Traceback (most recent call last):
  File ".\enable-checkpoint.py", line 24, in <module>
    probes.addCheckpoint(checkpoint["CheckPointID"], probe, user, secret)
  File "C:\code\uptrends\probes.py", line 19, in addCheckpoint
    checkpoints = json.loads(probe["Checkpoints"])
  File "C:\Users\jloeffler\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jloeffler\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```

**Comment by jmloeffler** [comment]
With the "Use only primary checkpoints option checked":
`"Checkpoints": "{\"Checkpoints\":[2,4,8,9,10,11,12,26,28,29,31,35,38,45,48,54,55,57,68,72,73,76,81,84,99,101,105,116,120,121,123,133,137,147,162,163],\"CapabilityFilters\":[\"PrimaryServer\"]}",`

Without the option checked:
`"Checkpoints": "2,4,8,9,10,11,12,26,28,29,31,35,38,45,48,54,55,57,68,72,73,76,81,84,99,101,105,116,120,121,123,133,137,147,162,163",`

**Comment by jmloeffler** [comment]
This does not seem to be an issue any longer with the v4 api.
